### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by shayanb** [smallbraineng/words3-contracts-v0#1]
While trying to submit a word, the proof step is done and the UI is showing "Awaiting move confirmation (check your wallet)..." However nothing happens. 

Here is the console log error:
<img width="1146" alt="Screen Shot 2022-11-24 at 1 59 17 PM" src="https://user-images.githubusercontent.com/309108/203851140-9ab3d43b-3277-447a-827e-02b7e09399c0.png">

**Comment by isaac-art** [comment]
i get similar on ~70% of attempts to play words, some go through and prompt the wallet but most fail.

**Comment by smallbraineng** [comment]
Thanks for playing and the feedback. I believe this error is a client side error related to the frontend not displaying some tiles. This causes invalid move generation from the client (because either letters are being placed in incorrect locations, or the bounds submitted from the client are incorrect). 

This has recently been fixed. @shayanb and @isaac-art can you confirm by checking what move you were making and seeing whether the area around it has been updated correctly. If not, could you screenshot the move that is not working and the send the location of it as well?

**Comment by shayanb** [comment]
This is one of the words that I had an issue the first time that still exists (starting at (3, -3)).

<img width="1199" alt="Screen Shot 2022-11-28 at 10 45 47 AM" src="https://user-images.githubusercontent.com/309108/204320770-782fe411-5353-4ec7-ac6f-76d49605e2a3.png">

**Comment by smallbraineng** [comment]
Ah, thanks for sharing.
All cross-words need to be valid as well. So this will not go through, for example, because "PG" is not a valid word. 
This should be messaged better on the client (and will be in v2)
